datasets:
  vlep: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /nas-ssd/shoubin/datasets/vlep/train.json
          storage: /nas-ssd/shoubin/datasets/vlep/train.json
        val:
          url: /nas-ssd/shoubin/datasets/vlep/val.json
          storage: /nas-ssd/shoubin/datasets/vlep/val.json
        test:
          url: /nas-ssd/shoubin/datasets/vlep/val.json
          storage: /nas-ssd/shoubin/datasets/vlep/val.json
      videos:
        storage: /nas-hdd/shoubin/videos/charades/Charades_v1_480/