datasets:
  msrvttmc: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      # no training data for this dataset
      annotations:
        train:
          url: /nas-ssd/shoubin/datasets/msrvttmc/val.json
          storage: /nas-ssd/shoubin/datasets/msrvttmc/val.json
        val:
          url: /nas-ssd/shoubin/datasets/msrvttmc/val.json
          storage: /nas-ssd/shoubin/datasets/msrvttmc/val.json
        test:
          url: /nas-ssd/shoubin/datasets/msrvttmc/val.json
          storage: /nas-ssd/shoubin/datasets/msrvttmc/val.json
      videos:
        storage: /nas-hdd/tarbucket/terran/data/msrvtt/videos/all/