datasets:
  perception_test: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    modality_type: 'rgb' # [RGB|D|OF|SN]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /nas-ssd/shoubin/datasets/perception_test/train.json
          storage: /nas-ssd/shoubin/datasets/perception_test/train.json
        val:
          url: /nas-ssd/shoubin/datasets/perception_test/val.json
          storage: /nas-ssd/shoubin/datasets/perception_test/val.json
        test:
          url: /nas-ssd/shoubin/datasets/perception_test/val.json
          storage: /nas-ssd/shoubin/datasets/perception_test/val.json
      videos:
        storage: /nas-hdd/shoubin/frames/perception/